services:

  postgres-db:
    image: postgres:16
    container_name: kt_postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  customer-service:
    build:
      context: ./customer_service
    container_name: kt_customer_service
    restart: unless-stopped
    depends_on:
      - postgres-db
      - laptop-service
      - mobile-service
    environment:
      DB_NAME: customer_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: postgres-db
      DB_PORT: 5432
      FORCE_SCRIPT_NAME: /customer
      LAPTOP_SERVICE_URL: http://laptop-service:8000
      MOBILE_SERVICE_URL: http://mobile-service:8000

  staff-service:
    build:
      context: ./staff_service
    container_name: kt_staff_service
    restart: unless-stopped
    depends_on:
      - postgres-db
    environment:
      DB_NAME: staff_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: postgres-db
      DB_PORT: 5432
      FORCE_SCRIPT_NAME: /staff
      LAPTOP_SERVICE_URL: http://laptop-service:8000
      MOBILE_SERVICE_URL: http://mobile-service:8000

  laptop-service:
    build:
      context: ./laptop_service
    container_name: kt_laptop_service
    restart: unless-stopped
    depends_on:
      - postgres-db
    environment:
      DB_NAME: laptop_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: postgres-db
      DB_PORT: 5432

  mobile-service:
    build:
      context: ./mobile_service
    container_name: kt_mobile_service
    restart: unless-stopped
    depends_on:
      - postgres-db
    environment:
      DB_NAME: mobile_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: postgres-db
      DB_PORT: 5432

  chatbot-service:
    build:
      context: ./chatbot_service
    container_name: kt_chatbot_service
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    container_name: kt_api_gateway
    restart: unless-stopped
    depends_on:
      - customer-service
      - staff-service
      - laptop-service
      - mobile-service
      - chatbot-service
    ports:
      - "8080:80"

volumes:
  postgres_data:
